#************Kubernetes name.YML  files***************************************************************

kind: Pod                              
apiVersion: v1                     
metadata:                           
  name: testpod                  
spec:                                    
  containers:                      
    - name: c00                     
      image: ubuntu              
      command: ["/bin/bash", "-c", "while true; do echo Hello-Chaudhry; sleep 5 ; done"]
  restartPolicy: Never         # Defaults to Always

# kubectl apply -f SimplePod1.yml # After write above file in Vim Editor. Run this command for pod running. 
